# Site settings
title: Rafael Schena
email: rafaelschena@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Engenheiro Eletricista. Cientista de Dados."
keywords: "engineer, data scientist, engenheiro, cientista de dados, inteligência artificial"
skills: "Engenheiro Eletricista. Cientista de Dados. Mestrando em Ciência da Computação"
meta_author: Schena Rafael
phone: +55(38)99175-8891

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: AFAAB9 #80B3FF
  primary-rgb: "175, 170, 185" #"128,179,255"
  secondary: 1B9AAA #FD6E8A
  secondary-dark: 363636 #A2122F

# About settings
about:
  text-1: "Engenheiro Eletricista formado pela Universidade de Brasília em 2007. Possui experiência na área de manutenção industrial, onde atuou por 3 anos na área de mineração (Votorantim Metais) e 6 anos na área de óleo e gás (Petrobras Transporte S.A.). Possui especialização em equipamentos elétricos industriais da indústria de óleo e gás natural. Nas atividades como engenheiro, sempre atuou com análise de dados, inclusive com a metodologia 6 Sigma."
  text-2: "Seus interesses maiores estão em desenvolver aplicações de Ciência de Dados e Inteligência Artificial para negócios, especialmente aplicações para o mercado financeiro, indústria 4.0, indústria de energia e manutenção industrial. Entusiasta da área de Ciência de Dados, atualmente é mestrando em Ciência da Computação na Universidade Federal do Rio Grande do Sul (UFRGS), pesquisa na área de Inteligência Artificial e Mineração de Dados em um projeto desta universidade visando o desenvolvimento de Gêmeos Digitais de plataformas de petróleo."

# Habilidades settings
habilidades:
  text-1: <b>Proficiente em:</b><br />
            <ul>
            <li>Ciência de Dados</li>
            <li><i>Machine Learning</i></li>
            <li>Python</li>
            <li>R</li>
            <li>Apache Spark</li>
            <li>Apache Hadoop</li>
            </ul>
  text-2: <b>Familiar com:</b><br />
            <ul>
            <li>Engenharia de Dados</li>
            <li>MongoDB</li>
            <li><i>Deep Learning</i></li>
            <li>Tensorflow</li>
            <li>Design de <i>Dashboards</i></li>
            <li>SQL</li>
            </ul>

# Curriculo settings
curriculo:
  text-1: <b>Formação</b><br />
            <ul>
            <li>Mestrado em Ciência da Computação - Universidade Federal do Rio Grande do Sul (UFRGS) -
            (2021- presente)</li><br />
            <li>Pós-graduação em Equipamentos Elétricos Aplicados à Indústria de Petróleo e Gás Natural -
            (2012-2013)</li><br />
            <li>Engenheiro Eletricista - Universidade de Brasília (UnB) - (2003-2007)</li></ul><br />
            <br />
          <b>Cursos complementares</b><br />
            <ul>
            <li>Big Data Analytics com R e MicrosoftAzure Machine Learning<br />Data Science Academy - Novembro/2020</li><br />
            <li>Big Data Fundamentos 2.0<br />Data Science Academy - Setembro/2020</li><br />
            <li>Introdução à Ciência de Dados 2.0<br />Data Science Academy - Setembro/2020</li><br />
            <li>Python Fundamentos para Análise de Dados<br />Data Science Academy - Agosto/2020</li><br />
            <li>Green Belt - Lean Six Sigma<br />Setec Consulting Group - Junho/2016</li>
            </ul>

  text-2: <b>Experiências</b><br />
            <ul>
            <li>Giraffas - Franqueado<br />
                (Junho/2018 a Maio/2020)</li><br />
            <li>Petrobras Transporte S.A. - Engenheiro de Equipamentos<br />
                (Maio/2012 a Maio/2018)</li><br />
            <li>Escola Técnica de Paracatu (Unitec) - Professor<br />
                (Junho/2011 a Abril/2012)</li><br />
            <li>Votorantim Metais - Engenheiro<br />
                (Janeiro/2008 a Março/2011)<br />
            </ul>
            <b>Mais detalhes em:<br />
            <a href="https://www.linkedin.com/in/rafaelschena/" target="_blank" style="color:blue">https://www.linkedin.com/in/rafaelschena/</a></b>


# Footer settings
footer:
  copyright: Dr. Henry Jekyll | 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'
  location: Onde me encontrar
  social: Meu trabalho na Web
  credits: Other Languages

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://youtube.com
  - title: linkedin
    url: https://www.linkedin.com/in/rafaelschena/
  - title: github
    url: https://github.com/rafaelschena
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Porto Alegre
  - line: Rio Grande do Sul - Brasil

# Credits content
credits: '<a href="http://startbootstrap.com" style="color:white">English</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
