version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Streamlit.dockerfile
    ports:
      - "8501:8501"  # Porta para o app Streamlit
    volumes:
      - .:/app       # Monta o volume local para desenvolvimento
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501

  stlite-static:
    build:
      context: .
      dockerfile: Stlite.dockerfile
    ports:
      - "8080:8080"  # Porta para o app estático
